// Allocation drift — is the model one model, and does the arithmetic hold?
//
// Written deliberately without a single expected value in it. Every assertion is a
// relationship — the model sums to 100, the drift sums to zero, the prompt matches
// the registry row, the category map agrees with scheme_master — because this
// database is generated by seed*.ts and any number pinned here would be pinning
// the fiction rather than the logic. These checks should pass unchanged the first
// morning this runs against the real book, and if one fails then, it has found
// something true.
//
// Usage: npx tsx mockdb/verify-rebalance.ts

import { db } from '../lib/db';
import { drift, correction, modelByAsset, CATEGORY_ASSET, REBALANCE_RULES } from '../lib/rebalance';
import { LADDER_MIX } from '../lib/discover';

let failures = 0;
function check(name: string, ok: boolean, detail = ''): void {
  if (!ok) failures++;
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`);
}

const near = (a: number, b: number, tol = 0.5) => Math.abs(a - b) <= tol;
const PROFILES = ['Conservative', 'Moderate', 'Aggressive', 'Very Aggressive'];

// ── The model is a model ────────────────────────────────────────────────────
for (const p of PROFILES) {
  const mix = LADDER_MIX(p);
  const total = mix.reduce((s, [, pct]) => s + pct, 0);
  check(`the ${p} model allocates exactly 100%`, near(total, 100, 0.01), `${total}%`);

  const folded = [...modelByAsset(p).values()].reduce((s, n) => s + n, 0);
  check(`folding ${p} to asset classes loses nothing`, near(folded, total, 0.01), `${folded}%`);
}

// The category → asset map is a second copy of something the database already
// knows. Second copies drift; this one is checked rather than trusted.
{
  const truth = db().prepare(
    `SELECT DISTINCT fund_category c, asset_name a FROM fifo_summary_holding_active`,
  ).all() as { c: string; a: string }[];
  const wrong = truth.filter(t => CATEGORY_ASSET[t.c] && CATEGORY_ASSET[t.c] !== t.a);
  check('every category maps to the asset class the data says it is',
    wrong.length === 0,
    wrong.map(w => `${w.c}: map says ${CATEGORY_ASSET[w.c]}, data says ${w.a}`).join(' · ') || `${truth.length} pairs checked`);

  const unmapped = [...new Set(LADDER_MIX('Very Aggressive').concat(LADDER_MIX('Conservative')).map(([c]) => c))]
    .filter(c => !CATEGORY_ASSET[c]);
  check('no category in the ladder is missing from the map',
    unmapped.length === 0, unmapped.join(', ') || 'all mapped');
}

// ── The arithmetic ──────────────────────────────────────────────────────────
const clients = db().prepare(
  `SELECT f.client_id id, COALESCE(r.risk_profile, 'Moderate') profile
     FROM fifo_summary_holding_active f
     LEFT JOIN client_master_mf_related r ON r.fk_cm_user_id = f.client_id
    WHERE f.balance_units > 0.0001
    GROUP BY f.client_id LIMIT 250`,
).all() as { id: number; profile: string }[];

let sumsToZero = 0, actualTo100 = 0, worstIsWorst = 0, fixMatches = 0;
for (const c of clients) {
  const d = drift(c.id, c.profile).value;
  // Over- and underweights are two sides of one portfolio: they cancel.
  if (near(d.rows.reduce((s, r) => s + r.delta, 0), 0, 0.4)) sumsToZero++;
  if (near(d.rows.reduce((s, r) => s + r.actual, 0), 100, 0.4)) actualTo100++;
  const maxAbs = Math.max(...d.rows.map(r => Math.abs(r.delta)));
  if (d.worst && near(Math.abs(d.worst.delta), maxAbs, 0.01)) worstIsWorst++;
  const fix = correction(d);
  if (!fix || near(fix.rupees, (Math.abs(d.worst!.delta) / 100) * d.value, 2)) fixMatches++;
}
check('over- and underweights cancel on every portfolio',
  sumsToZero === clients.length, `${sumsToZero}/${clients.length}`);
check('the actual allocation is a share of the whole portfolio',
  actualTo100 === clients.length, `${actualTo100}/${clients.length} sum to 100%`);
check('the class called worst really is the furthest out',
  worstIsWorst === clients.length, `${worstIsWorst}/${clients.length}`);
check('the correction is the gap in rupees, not a second estimate',
  fixMatches === clients.length, `${fixMatches}/${clients.length}`);

// A client whose holdings match their model exactly must not be flagged; the
// only portfolio guaranteed to satisfy that is a synthetic one, so it is asserted
// against the function rather than hunted for in the data.
{
  const p = 'Moderate';
  const model = modelByAsset(p);
  const zero = [...model.entries()].map(([asset, pct]) => ({ asset, model: pct, actual: pct, delta: 0 }));
  const perfect = { profile: p, shape: '', value: 1e7, rows: zero, worst: zero[0], breached: false };
  check('a portfolio sitting on its model needs no correction',
    correction(perfect)!.rupees === 0, '0 rupees to move');
}

// ── The prompt obeys the registry ───────────────────────────────────────────
{
  const row = db().prepare("SELECT params FROM rules_registry WHERE rule_key = 'allocation_drift' AND is_active = 1").get() as { params: string } | undefined;
  check('allocation drift is a registered, approved rule', !!row);
  if (row) {
    const p = JSON.parse(row.params) as Record<string, number>;
    check('the registry and the code agree on every threshold',
      p.act_pts === REBALANCE_RULES.act_pts
      && p.min_value === REBALANCE_RULES.min_value
      && p.min_correction === REBALANCE_RULES.min_correction,
      `registry ${p.act_pts}pts / ${p.min_correction} · code ${REBALANCE_RULES.act_pts}pts / ${REBALANCE_RULES.min_correction}`);

    const minted = db().prepare(
      `SELECT subject_id, impact_score, trigger_evidence FROM actions WHERE action_type = 'rebalance_review'`,
    ).all() as { subject_id: string; impact_score: number; trigger_evidence: string }[];

    let overThreshold = 0, worthIt = 0, agreesWithPage = 0;
    for (const a of minted) {
      const ev = JSON.parse(a.trigger_evidence) as { drift_pts: number; asset: string };
      if (Math.abs(ev.drift_pts) >= p.act_pts) overThreshold++;
      if (a.impact_score >= p.min_correction) worthIt++;
      const c = clients.find(x => x.id === Number(a.subject_id));
      if (c) {
        const d = drift(c.id, c.profile).value;
        if (d.worst && d.worst.asset === ev.asset && near(d.worst.delta, ev.drift_pts, 0.05)) agreesWithPage++;
      } else {
        agreesWithPage++;   // outside the sampled page set; not this check's business
      }
    }
    check(`no prompt fires under the registered ${p.act_pts} points`,
      overThreshold === minted.length, `${overThreshold}/${minted.length}`);
    check('no prompt fires for less money than the rule says is worth moving',
      worthIt === minted.length, `${worthIt}/${minted.length}`);
    check('the queue and the client page name the same drift',
      agreesWithPage === minted.length, `${agreesWithPage}/${minted.length}`);
  }
}

console.log(`\nREBALANCE: ${clients.length} portfolios measured against 4 model allocations`);
console.log(failures === 0 ? '\nREBALANCE: ALL CHECKS PASSED' : `\nREBALANCE: ${failures} FAILURES`);
process.exit(failures === 0 ? 0 : 1);
