import { db } from './db';
import { LADDER_MIX, LADDER_NAME } from './discover';
import type { Figure } from './queries';

// Drift: how far a portfolio has walked away from the allocation its own risk
// profile calls for.
//
// The model is not a second opinion invented here. It is the same ladder the
// Discover questions land on, read through the profile already on file — one
// target allocation in the product, whichever screen asked for it.
//
// Measured at asset-class level, not fund category, because that is the level a
// conversation happens at: nobody rebalances out of Flexi Cap into Large Cap, they
// take equity down and debt up. Category drift is a fund-selection question and it
// belongs on the analysis tab, not in a rebalancing prompt.
//
// One warning for whoever meets the real book. Every threshold here is argued from
// what a switch costs, never from how many prompts it produces against
// mockdb/jhaveri.db — that database is generated by seed*.ts and its portfolios
// are shallow by construction (one to three funds each), so almost every client in
// it sits far from any five-class model. That is a fact about the seed. What the
// real book does to these numbers is a question for the real book, and the rule
// lives in rules_registry precisely so the answer can be changed there.

export const REBALANCE_RULES = {
  /** Drift worth naming on the client's page. */
  warn_pts: 5,
  /** Drift worth a prompt in the broker's queue. Percentage POINTS, not percent:
   *  55% equity against a 45% model is 10 points out, which is the number a
   *  reader checks with subtraction rather than division. */
  act_pts: 10,
  /** Below this a percentage-point gap is noise on a small portfolio. */
  min_value: 100000,
  /**
   * What the correction has to be worth before it becomes a prompt rather than a
   * fact on the client's page.
   *
   * Reasoned, NOT fitted to the prototype's data: a switch costs the client exit
   * load and a capital-gains event, and costs the broker a call. Below roughly a
   * lakh of movement the tax drag on the switch is a material share of the
   * correction itself, so the prompt would be asking someone to pay to be tidy.
   * Five lakh is the round number above that where a rebalance is unambiguously
   * worth both parties' time — and it is a number to argue with on those grounds,
   * in the registry row, not by counting how many prompts it happens to produce
   * in a seeded database.
   */
  min_correction: 500000,
  version: 'rebalance-v1 · model from discover LADDER via risk profile',
} as const;

export interface DriftRow {
  asset: string;
  model: number;
  actual: number;
  /** actual − model, in percentage points. Positive means overweight. */
  delta: number;
}

export interface Drift {
  profile: string;
  shape: string;
  value: number;
  rows: DriftRow[];
  /** The single asset class furthest from its model, by absolute points. */
  worst: DriftRow | null;
  breached: boolean;
}

/**
 * The model, folded to asset class, without touching the database — so the seed
 * can mint against exactly the number the page renders. The category → asset map
 * is checked against scheme_master in verify-rebalance rather than trusted.
 */
export function modelByAsset(profile: string): Map<string, number> {
  const out = new Map<string, number>();
  for (const [category, pct] of LADDER_MIX(profile)) {
    const asset = CATEGORY_ASSET[category] ?? 'Other';
    out.set(asset, (out.get(asset) ?? 0) + pct);
  }
  return out;
}

/** Every category the ladder can name. Verified against scheme_master. */
export const CATEGORY_ASSET: Record<string, string> = {
  Liquid: 'Debt', 'Corporate Bond': 'Debt',
  'Arbitrage Fund': 'Hybrid', 'Aggressive Hybrid': 'Hybrid',
  'Large Cap': 'Equity', 'Flexi Cap': 'Equity', 'Mid Cap': 'Equity',
  'Small Cap': 'Equity', 'ELSS (Tax Savings)': 'Equity',
  'Gold FoF': 'Commodities',
};

/**
 * Every asset class either side of the comparison appears, including the ones at
 * zero: a client holding no debt against a model that wants 15% has a 15-point
 * gap, and dropping the row because the holding is missing is exactly how that
 * gap stays invisible.
 */
export function drift(clientId: number, profile: string): Figure<Drift> {
  const held = db().prepare(
    `SELECT asset_name asset, SUM(present_market_value) v
       FROM fifo_summary_holding_active
      WHERE client_id = ? AND balance_units > 0.0001
      GROUP BY asset_name`,
  ).all(clientId) as { asset: string; v: number }[];

  const value = held.reduce((s, r) => s + r.v, 0);
  const model = modelByAsset(profile);

  const actual = new Map<string, number>();
  for (const r of held) actual.set(r.asset, value > 0 ? (r.v / value) * 100 : 0);

  const rows: DriftRow[] = [...new Set([...model.keys(), ...actual.keys()])]
    .map(asset => {
      const m = Math.round((model.get(asset) ?? 0) * 10) / 10;
      const a = Math.round((actual.get(asset) ?? 0) * 10) / 10;
      return { asset, model: m, actual: a, delta: Math.round((a - m) * 10) / 10 };
    })
    .sort((x, y) => Math.abs(y.delta) - Math.abs(x.delta));

  const worst = rows[0] ?? null;
  return {
    value: {
      profile,
      shape: LADDER_NAME(profile),
      value,
      rows,
      worst,
      breached: value >= REBALANCE_RULES.min_value
        && !!worst && Math.abs(worst.delta) >= REBALANCE_RULES.act_pts,
    },
    tag: 'rule',
    sql: `${REBALANCE_RULES.version}\nmodel = the ladder rung this risk profile maps to, folded to asset class`
      + `\nactual = fifo_summary_holding_active.present_market_value by asset_name`
      + `\nbreach at ${REBALANCE_RULES.act_pts} percentage points on any one class`,
    sources: ['client_master_mf_related.risk_profile', 'fifo_summary_holding_active.asset_name', '.present_market_value'],
  };
}

/**
 * What actually has to move to close the worst gap. A prompt that says "you are
 * 14 points overweight equity" is a measurement; this is the instruction.
 */
export function correction(d: Drift): { asset: string; direction: 'reduce' | 'add'; rupees: number } | null {
  if (!d.worst || d.value <= 0) return null;
  return {
    asset: d.worst.asset,
    direction: d.worst.delta > 0 ? 'reduce' : 'add',
    rupees: Math.round((Math.abs(d.worst.delta) / 100) * d.value),
  };
}
